// Code generated by builder, DO NOT EDIT.
package main

import "database/sql"

type FooBuilder struct {
	foo Foo
}

func NewFooBuilder() *FooBuilder {
	return &FooBuilder{}
}

// WithID sets id.
func (b FooBuilder) WithID(id int64) FooBuilder {
	b.foo.id = id
	return b
}

// WithName sets name.
func (b FooBuilder) WithName(name string) FooBuilder {
	b.foo.name = name
	return b
}

// WithAge sets age.
func (b FooBuilder) WithAge(age sql.NullInt64) FooBuilder {
	b.foo.age = age
	return b
}

// WithValid sets valid.
func (b FooBuilder) WithValid(valid bool, valid1 bool) FooBuilder {
	if valid1 {
		b.foo.valid = &valid
	}
	return b
}

// WithURL sets url.
func (b FooBuilder) WithURL(url string) FooBuilder {
	b.foo.url = url
	return b
}

// WithRealAge sets realAge.
func (b FooBuilder) WithRealAge(realAge int64, valid bool) FooBuilder {
	if valid {
		b.foo.realAge = &realAge
	}
	return b
}

// Build returns Foo.
func (b FooBuilder) Build() Foo {
	return b.foo
}
