// Code generated by builder, DO NOT EDIT.
package main

import "fmt"

type SimpleBuilder struct {
	simple Simple
	fields map[string]bool
}

func NewSimpleBuilder() *SimpleBuilder {
	return &SimpleBuilder{fields: map[string]bool{"name": false}}
}

// WithName sets name.
func (b SimpleBuilder) WithName(name string) SimpleBuilder {
	b.setOrPanic("name")
	b.simple.name = name
	return b
}

// Build returns Simple.
func (b SimpleBuilder) Build() Simple {
	for field, isSet := range b.fields {
		if !isSet {
			panic(fmt.Sprintf("builder.BuildErr: %q not set", field))
		}
	}
	return b.simple
}

// Build returns Simple.
func (b SimpleBuilder) BuildPartial() Simple {
	return b.simple
}

// setOrPanic sets the fields only if it has not yet been set. It will panic when calling it twice.
func (b *SimpleBuilder) setOrPanic(field string) {
	c := b.cloneFields()
	if c[field] {
		panic(fmt.Sprintf("builder.BuildErr: cannot set %q twice", field))
	}
	c[field] = true
	b.fields = c
}

// cloneFields clone the fields to avoid mutation
func (b SimpleBuilder) cloneFields() map[string]bool {
	result := make(map[string]bool)
	for k, v := range b.fields {
		result[k] = v
	}
	return result
}
